### ISSUE TITLE
Please explain the format of HZMetro and SHMetro datasets

### ISSUE THREAD

**Issue by DarkstartsUp** [ivechan/PVCGN#1]
Dear author, thank you for your wonderful paper and your new dataset. However, I couldn't find a detailed description of the new HZMetro and SHMetro datasets format. Specifically, I don't understand the format of train/val/test.pkl in the dataset folder. These pkl files contain 4 keys of ['x', 'y', 'xtime', 'ytime'], and the value of key 'x' and 'y' is in the shape of (N, 4, 80, 2). What are the meanings of 'x' and 'y'? And what do the different dimensions of value mean? Looking forward to your reply.

**Comment by liulingbo918** [comment]
Thanks for your attention. We have updated a README for our datasets at https://github.com/HCPLab-SYSU/PVCGN/tree/master/data.

**Comment by DarkstartsUp** [comment]
Thanks a lot!
