### ISSUE TITLE
About dataset 

### ISSUE THREAD

**Issue by Neoyanghc** [ivechan/PVCGN#2]
hi, thanks a lot for your datasets, but l only get the processed data, where can i get the data with the userid and OD informations,
We are expecting a reply ,  thanks

**Comment by liulingbo918** [comment]
The original data of Hangzhou Metro can be found at https://tianchi.aliyun.com/competition/entrance/231708/information. 
The original data of Shanghai Metro cannot be released due to the copyright issue.

> hi, thanks a lot for your datasets, but l only get the processed data, where can i get the data with the userid and OD informations,
> We are expecting a reply , thanks

**Comment by Neoyanghc** [comment]
Thanks a lot

**Comment by Neoyanghc** [comment]
hi，the data is not available at the url because the time limitation， could you please help me to give a baiduDisk or email me(2011258@tongji.edu.cn or 1178894864@qq.com)
thanks a lot，

**Comment by liulingbo918** [comment]
> The processed OD data can be found in https://github.com/HCPLab-SYSU/HIAM
