### ISSUE TITLE
Some questions about predicting the time step.

### ISSUE THREAD

**Issue by custsyz** [ivechan/PVCGN#4]
I'm sorry to bother you, but I'm just beginning to get in touch with deep learning. I have some doubts, hope you could reply me in your spare time. 
The first question is, how to understand the 15-minute, 30-minute, 45-minute, 60-minute experiment results in your paper? The second question is, does your model support passenger flow forecasting at an interval of five minutes, and if so, what should I do? 
Thank you very much again and look forward to your reply~

**Comment by ivechan** [comment]
Hi @custsyz 
1. 15 minutes indicates the flow of people from 0th  to 15th minute.
30 minutes indicates the flow of people from the 15th minute to the 30th minute, and so on.

2. It supports I think. 
But it involves another question, whether the 5-minute traffic flow is more statistically significant.

**Comment by custsyz** [comment]
Thank you very much for your kind heartness on taking time answering my mind of doubt from your busy shedule.I really appreciate it and here I would like to offer you my thankfulness most sincerely.
